---
- name: Update package lists and install NGINX
  hosts: all
  become: yes

  tasks:
    - name: Update APT package lists
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Ensure NGINX is started and enabled
      service:
        name: nginx
        state: restarted
        enabled: yes
