---
- hosts: all
  become: yes
  tasks:
    - name: Upgrade the server
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install Ookla Speedtest CLI repository
      shell: curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | bash

    - name: Install Speedtest CLI
      shell: sudo apt-get install speedtest

    - name: Test bandwidth with Speedtest and save result
      shell: speedtest --server-id 20144 > /opt/speedtest_result.txt   

    - name: Install fio
      apt:
        name: fio
        state: present

    - name: Test read and write speed with fio and save result
      shell: fio --ioengine=libaio --direct=1 --randrepeat=0 --refill_buffers --end_fsync=1 --rwmixread=70 --filename=/home/onnorokom/.kdiskmark.tmp --name=write --size=1024m --bs=4k --rw=write --iodepth=32 --numjobs=16 --group_reporting --time_based --runtime=300 > /opt/fio_test_result.txt
      shell: fio --ioengine=libaio --direct=1 --randrepeat=0 --refill_buffers --end_fsync=1 --rwmixread=70 --filename=/home/onnorokom/.kdiskmark.tmp --name=read --size=1024m --bs=4k --rw=read --iodepth=32 --numjobs=16 --group_reporting --time_based --runtime=300 > /opt/fio_test_result.txt

    - name: Install Telegraf
      apt:
        name: telegraf
        state: present

    - name: Copy telegraf-ostream.conf.j2 content to telegraf.conf
      template:
        src: telegraf-ostream.conf.j2
        dest: /etc/telegraf/telegraf.conf

    - name: Restart Telegraf
      systemd:
        name: telegraf
        state: restarted

    - name: Install Logstash GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Add Logstash repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present

    - name: Install Logstash
      apt:
        name: logstash
        state: present
        update_cache: yes

    - name: Copy logstash-ostream.conf.j2 content to ostream.conf
      template:
        src: logstash-ostream.conf.j2
        dest: /etc/logstash/conf.d/ostream.conf

    - name: Create __udvash-unmesh_com.ca-bundle file in /etc/logstash
      template:
        src: ostream-cert.conf.j2
        dest: /etc/logstash/__udvash-unmesh_com.ca-bundle

    - name: Install traceroute
      apt:
        name: traceroute
        state: present

    - name: Copy sysctl.conf.j2 content to /etc/sysctl.conf
      template:
        src: sysctl.conf.j2
        dest: /etc/sysctl.conf

    - name: Refresh the kernel parameters
      command: sysctl -p
